language: rust
rust:
  - stable

os:
  - linux

matrix:
  fast_finish: true

before_script:
  - rustup component add clippy

script:
  - cargo build --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose -- --test-threads=1

cache:
  cargo

git:
  depth: 1
