language: rust
rust:
  - stable

matrix:
  fast_finish: true

addons:
  apt:
    packages: libgpgme11-dev

before_script:
  - rustup component add clippy

script:
  - cargo build --verbose
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose -- --test-threads=1

cache:
  cargo

git:
  depth: 1
