language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
     - libgpgme11-dev

env:
  - CARGO_INCREMENTAL=0 RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads"

before_cache: |
  if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
    cargo install grcov -f
  fi


before_script:
  - if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then rustup component add clippy; fi
  - if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then rustup component add rustfmt; fi


script:
  - if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo clippy --all-targets --all-features -- -D warnings; fi
  - if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo fmt --all -- --check; fi
  - cargo test --verbose -- --test-threads=1

cache:
  cargo

git:
  depth: 1

after_success: |
  zip -0 ccov.zip `find . \( -name "vd-verifier*.gc*" \) -print`;
  grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
  bash <(curl -s https://codecov.io/bash) -f lcov.info;
