---
addons:
  apt:
    packages:
      - libgpgme11-dev
      - libgpg-error-dev
      - curl
after_success: |
  zip -0 ccov.zip `find . \( -name "vd_verifier*.gc*" \) -print`;
  ./grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore-dir "/*" -o lcov.info;
  bash <(curl -s https://codecov.io/bash) -f lcov.info;
before_install:
  - "if [[ \"$TRAVIS_RUST_VERSION\" == \"nightly\" ]]; then \"curl -L \\\"https://github.com/mozilla/grcov/releases/latest/download/grcov-linux-x86_64.tar.bz2\\\" | tar jxf -\""
before_script:
  - "if [[ ! \"$TRAVIS_RUST_VERSION\" == \"nightly\" ]]; then rustup component add clippy; fi"
  - "if [[ ! \"$TRAVIS_RUST_VERSION\" == \"nightly\" ]]; then rustup component add rustfmt; fi"
cache: cargo
git:
  depth: 1
language: rust
matrix:
  allow_failures:
    -
      rust: nightly
  fast_finish: true
  include:
    -
      env: "CARGO_FLAGS=\"--features nightly\" CARGO_INCREMENTAL=0 RUSTFLAGS=\"-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Zno-landing-pads\""
      rust: nightly
rust:
  - stable
  - beta
script:
  - "if [[ ! \"$TRAVIS_RUST_VERSION\" == \"nightly\" ]]; then cargo clippy --all-targets --all-features -- -D warnings; fi"
  - "if [[ ! \"$TRAVIS_RUST_VERSION\" == \"nightly\" ]]; then cargo fmt --all -- --check; fi"
  - "cargo build"
  - "cargo test --verbose -- --test-threads=1"
