language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

addons:
  apt:
    packages:
     - libgpgme11-dev
     - libssl-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi


before_script:
  - if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then rustup component add clippy; fi
  - if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then rustup component add rustfmt; fi


script:
  - cargo clean
  - if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo clippy --all-targets --all-features -- -D warnings; fi
  - if [[ ! "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo fmt --all -- --check; fi
  - cargo test --verbose -- --test-threads=1

cache:
  cargo

git:
  depth: 1

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi