[package]
name = "vd-verifier"
description = "The other half of vd browser extension"
version = "0.2.2"
license = "GPL-3.0-or-later"
authors = ["matous"]
edition = "2018"
keywords = ["verify", "downloads", "browser", "firefox", "extension", ]
readme = "README.md"
repository = "https://github.com/mmatous/vd-verifier"
categories = ["cryptography"]
publish = false

[dependencies]
byteorder = "1"
failure = "0.1"
hex = "0.3"
md-5 = "0.8"
regex = "1"
serde_json = "1"
sha-1 = "0.8"
sha2 = "0.8"
structopt = { version = "0.2", default-features = false }

[profile.release]
lto = true
